# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2
     
     - name: Use Node.js
       uses: actions/setup-node@v1
       with:
         node-version: 14.x
     - run: xcode-select -p

     - name: Try Build
       run: ./not-exist-file.sh it bloke build
       
     - name: Start SSH via ngrok
       if: ${{ failure() }}
       uses: P3TERX/ssh2actions@main
       with:
        mode: ngrok
       env:
        # After sign up on the https://ngrok.com
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        # You can find this server region here: https://ngrok.com/docs#global-locations
        NGROK_REGION: us

        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

        # Send connection info to Telegram (optional)
        # You can find related documents here: https://core.telegram.org/bots
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h
       
       
